from racing_lines.australia import track_data as australia_data
from racing_lines.china import track_data as china_data
from racing_lines.japan import track_data as japan_data
from racing_lines.bahrain import track_data as bahrain_data
from racing_lines.saudi_arabia import track_data as saudi_arabia_data
from racing_lines.miami import track_data as miami_data
from racing_lines.imola import track_data as imola_data
from racing_lines.monaco import track_data as monaco_data
from racing_lines.canada import track_data as canada_data
from racing_lines.spain import track_data as spain_data
from racing_lines.austria import track_data as austria_data
from racing_lines.silverstone import track_data as silverstone_data
from racing_lines.hungary import track_data as hungary_data
from racing_lines.belgium import track_data as belgium_data
from racing_lines.netherlands import track_data as netherlands_data
from racing_lines.monza import track_data as monza_data
from racing_lines.azerbaijan import track_data as azerbaijan_data
from racing_lines.singapore import track_data as singapore_data
from racing_lines.usa import track_data as usa_data
from racing_lines.mexico import track_data as mexico_data
from racing_lines.brazil import track_data as brazil_data
from racing_lines.las_vegas import track_data as las_vegas_data
from racing_lines.qatar import track_data as qatar_data
from racing_lines.abu_dhabi import track_data as abu_dhabi_data


tracks = [
    {
        "name": "Australia",
        "map": "tracks/australia.png",
        "racing_line": australia_data["racing_line"],
        "drs_zones": australia_data["drs_zones"],
        "pit_lane": australia_data["pit_lane"],
        "sector_points": australia_data["sector_points"],
        "laps": 58,
        "length": 5278,
    },
    {
        "name": "China",
        "map": "tracks/china.png",
        "racing_line": china_data["racing_line"],
        "drs_zones": china_data["drs_zones"],
        "pit_lane": china_data["pit_lane"],
        "sector_points": china_data["sector_points"],
        "laps": 56,
        "length": 5451,
    },
    {
        "name": "Japan",
        "map": "tracks/japan.png",
        "racing_line": japan_data["racing_line"],
        "drs_zones": japan_data["drs_zones"],
        "pit_lane": japan_data["pit_lane"],
        "sector_points": japan_data["sector_points"],
        "laps": 53,
        "length": 5807,
    },
    {
        "name": "Bahrain",
        "map": "tracks/bahrain.png",
        "racing_line": bahrain_data["racing_line"],
        "drs_zones": bahrain_data["drs_zones"],
        "pit_lane": bahrain_data["pit_lane"],
        "sector_points": bahrain_data["sector_points"],
        "laps": 57,
        "length": 5412,
    },
    {
        "name": "Saudi Arabia",
        "map": "tracks/saudi_arabia.png",
        "racing_line": saudi_arabia_data["racing_line"],
        "drs_zones": saudi_arabia_data["drs_zones"],
        "pit_lane": saudi_arabia_data["pit_lane"],
        "sector_points": saudi_arabia_data["sector_points"],
        "laps": 50,
        "length": 6174,
    },
    {
        "name": "Miami",
        "map": "tracks/miami.png",
        "racing_line": miami_data["racing_line"],
        "drs_zones": miami_data["drs_zones"],
        "pit_lane": miami_data["pit_lane"],
        "sector_points": miami_data["sector_points"],
        "laps": 57,
        "length": 5410,
    },
    {
        "name": "Imola",
        "map": "tracks/imola.png",
        "racing_line": imola_data["racing_line"],
        "drs_zones": imola_data["drs_zones"],
        "pit_lane": imola_data["pit_lane"],
        "sector_points": imola_data["sector_points"],
        "laps": 63,
        "length": 4909,
    },
    {
        "name": "Monaco",
        "map": "tracks/monaco.png",
        "racing_line": monaco_data["racing_line"],
        "drs_zones": monaco_data["drs_zones"],
        "pit_lane": monaco_data["pit_lane"],
        "sector_points": monaco_data["sector_points"],
        "laps": 78,
        "length": 3337,
    },
    {
        "name": "Canada",
        "map": "tracks/canada.png",
        "racing_line": canada_data["racing_line"],
        "drs_zones": canada_data["drs_zones"],
        "pit_lane": canada_data["pit_lane"],
        "sector_points": canada_data["sector_points"],
        "laps": 70,
        "length": 4361,
    },
    {
        "name": "Spain",
        "map": "tracks/spain.png",
        "racing_line": spain_data["racing_line"],
        "drs_zones": spain_data["drs_zones"],
        "pit_lane": spain_data["pit_lane"],
        "sector_points": spain_data["sector_points"],
        "laps": 66,
        "length": 4657,
    },
    {
        "name": "Austria",
        "map": "tracks/austria.png",
        "racing_line": austria_data["racing_line"],
        "drs_zones": austria_data["drs_zones"],
        "pit_lane": austria_data["pit_lane"],
        "sector_points": austria_data["sector_points"],
        "laps": 71,
        "length": 4318,
    },
    {
        "name": "Silverstone",
        "map": "tracks/silverstone.png",
        "racing_line": silverstone_data["racing_line"],
        "drs_zones": silverstone_data["drs_zones"],
        "pit_lane": silverstone_data["pit_lane"],
        "sector_points": silverstone_data["sector_points"],
        "laps": 52,
        "length": 5891,
    },
    {
        "name": "Hungary",
        "map": "tracks/hungary.png",
        "racing_line": hungary_data["racing_line"],
        "drs_zones": hungary_data["drs_zones"],
        "pit_lane": hungary_data["pit_lane"],
        "sector_points": hungary_data["sector_points"],
        "laps": 70,
        "length": 4381,
    },
    {
        "name": "Belgium",
        "map": "tracks/belgium.png",
        "racing_line": belgium_data["racing_line"],
        "drs_zones": belgium_data["drs_zones"],
        "pit_lane": belgium_data["pit_lane"],
        "sector_points": belgium_data["sector_points"],
        "laps": 44,
        "length": 7004,
    },
    {
        "name": "Netherlands",
        "map": "tracks/netherlands.png",
        "racing_line": netherlands_data["racing_line"],
        "drs_zones": netherlands_data["drs_zones"],
        "pit_lane": netherlands_data["pit_lane"],
        "sector_points": netherlands_data["sector_points"],
        "laps": 72,
        "length": 4259,
    },
    {
        "name": "Monza",
        "map": "tracks/monza.png",
        "racing_line": monza_data["racing_line"],
        "drs_zones": monza_data["drs_zones"],
        "pit_lane": monza_data["pit_lane"],
        "sector_points": monza_data["sector_points"],
        "laps": 53,
        "length": 5793,
    },
    {
        "name": "Azerbaijan",
        "map": "tracks/azerbaijan.png",
        "racing_line": azerbaijan_data["racing_line"],
        "drs_zones": azerbaijan_data["drs_zones"],
        "pit_lane": azerbaijan_data["pit_lane"],
        "sector_points": azerbaijan_data["sector_points"],
        "laps": 51,
        "length": 6003,
    },
    {
        "name": "Singapore",
        "map": "tracks/singapore.png",
        "racing_line": singapore_data["racing_line"],
        "drs_zones": singapore_data["drs_zones"],
        "pit_lane": singapore_data["pit_lane"],
        "sector_points": singapore_data["sector_points"],
        "laps": 62,
        "length": 5063,
    },
    {
        "name": "USA",
        "map": "tracks/usa.png",
        "racing_line": usa_data["racing_line"],
        "drs_zones": usa_data["drs_zones"],
        "pit_lane": usa_data["pit_lane"],
        "sector_points": usa_data["sector_points"],
        "laps": 56,
        "length": 5513,
    },
    {
        "name": "Mexico",
        "map": "tracks/mexico.png",
        "racing_line": mexico_data["racing_line"],
        "drs_zones": mexico_data["drs_zones"],
        "pit_lane": mexico_data["pit_lane"],
        "sector_points": mexico_data["sector_points"],
        "laps": 71,
        "length": 4304,
    },
    {
        "name": "Brazil",
        "map": "tracks/brazil.png",
        "racing_line": brazil_data["racing_line"],
        "drs_zones": brazil_data["drs_zones"],
        "pit_lane": brazil_data["pit_lane"],
        "sector_points": brazil_data["sector_points"],
        "laps": 71,
        "length": 4309,
    },
    {
        "name": "Las Vegas",
        "map": "tracks/las_vegas.png",
        "racing_line": las_vegas_data["racing_line"],
        "drs_zones": las_vegas_data["drs_zones"],
        "pit_lane": las_vegas_data["pit_lane"],
        "sector_points": las_vegas_data["sector_points"],
        "laps": 50,
        "length": 6201,
    },
    {
        "name": "Qatar",
        "map": "tracks/qatar.png",
        "racing_line": qatar_data["racing_line"],
        "drs_zones": qatar_data["drs_zones"],
        "pit_lane": qatar_data["pit_lane"],
        "sector_points": qatar_data["sector_points"],
        "laps": 57,
        "length": 5419,
    },
    {
        "name": "Abu Dhabi",
        "map": "tracks/abu_dhabi.png",
        "racing_line": abu_dhabi_data["racing_line"],
        "drs_zones": abu_dhabi_data["drs_zones"],
        "pit_lane": abu_dhabi_data["pit_lane"],
        "sector_points": abu_dhabi_data["sector_points"],
        "laps": 58,
        "length": 5281,
    },
]
